### PR TITLE
add a date cli command

### PR DESCRIPTION
**Pull request by denis2342**
just a small change to test the waters.

### CODE REVIEW

**Comment by willsowerbutts** [comment]
Thanks!

**Comment by willsowerbutts** [comment]
PS what hardware are you running on?

**Comment by denis2342** [comment]
kiss030 with 33Mhz CPU and 66Mhz 256MB RAM.

**Comment by willsowerbutts** [comment]
I'll have to finish my ECB ethernet board so you can try out the IP stack then :)

**Comment by denis2342** [comment]
right now I use your usb-fifo board with a handwritten userland tool which feeds the ppp daemon. but yeah, I would take some of these boards.

**Pull request merged**
